include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    use_build_context_synchronously: false
    cancel_subscriptions: true
    close_sinks: true
    implementation_imports: false
    lines_longer_than_80_chars: false
    prefer_constructors_over_static_methods: false
    public_member_api_docs: false
    library_private_types_in_public_api: false
    prefer_final_parameters: true
    prefer_relative_imports: true
    always_use_package_imports: false
