name: teta_widgets
description: Official package of Teta
version: 0.0.16
homepage:
publish_to: builder.teta.so:8888

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  teta_core:
    git:
      url: git@github.com:andreabuttarelli/Teta.git
      path: teta_core
      ref: develop
  teta_repositories:
    git:
      url: git@github.com:andreabuttarelli/Teta.git
      path: teta_repositories
      ref: develop
  teta_cms:
    git:
      url: https://github.com/teta-so/cms-dart.git
      ref: main
  flutter_polyline_points:
    git:
      url: https://github.com/AndreiCosmaTeta/flutter_polyline_points.git
      ref: web

  # DB & Services
  supabase: ^0.3.6
  supabase_flutter: ^0.3.3
  http: 0.13.4
  github: 9.3.0
  socket_io_client: 2.0.0
  dart_airtable: 1.1.0
  mixpanel_analytics: 2.1.1

  # Bloc
  flutter_bloc: 7.3.3
  equatable: 2.0.3

  # Typography & Icons
  google_fonts: 2.3.3
  flutter_feather_icons: 2.0.0+1
  material_design_icons_flutter: 5.0.6595
  flutter_svg:
  fluentui_system_icons: 1.1.173
  font_awesome_flutter_named: 1.1.1
  line_icons: 2.0.1
  feather_icons: 1.2.0

  # UI
  hovering: 1.0.4
  graphview: 1.1.1
  transition: 2.0.2
  simple_animations: 4.2.0
  flutter_colorpicker: 1.0.3
  multi_split_view: 1.13.0
  focus_detector: 2.0.1
  sa3_liquid: 1.0.1
  flutter_staggered_animations: 1.0.0

  # Share & send
  mailto: 2.0.0
  url_launcher: 6.1.4
  clipboard: 0.1.3

  # Widgets
  auth_buttons: 2.0.4
  lottie: 1.3.0
  youtube_player_iframe: 2.3.0
  expandable: 5.0.1
  custom_refresh_indicator: 1.2.1
  liquid_swipe: 2.1.1
  map: 1.0.0
  latlng: 0.1.0
  webview_windows: 0.2.0
  badges: 2.0.3
  flutter_staggered_grid_view: 0.4.1
  paged_vertical_calendar: 1.1.3
  table_calendar: 3.0.7
  webviewx: 0.2.1
  tcard: 1.3.5
  concentric_transition: 1.0.3
  bouncing_widget: 2.0.0
  camera: ^0.10.0+3
  qr_flutter: 4.0.0
  barcode: 2.1.0
  barcode_widget: 2.0.1
  google_maps_flutter_web: 0.4.0+3
  google_maps_flutter: 2.2.1
  flutter_cache_manager: 3.3.0
  download_assets: 3.0.0
  mobile_scanner: 2.0.0
  gap: 2.0.0

  # Utils
  uuid: 3.0.6
  archive: 3.3.0
  path_provider: 2.0.11
  password_strength: 0.2.0
  nanoid: 1.0.0
  tinycolor: 1.0.3
  intl: 0.17.0
  math_expressions: 2.3.1
  path_drawing: 1.0.0
  nil: 1.1.1
  universal_ui: 0.0.8
  screenshot: 1.2.3
  feedback: 2.5.0
  cryptography: 2.0.5
  catcher: 0.6.9
  encrypt: 5.0.1
  after_layout: 1.2.0
  recase: 4.0.0
  version: 2.0.0
  fast_immutable_collections: 7.4.1
  enum_to_string: 2.0.1
  flutter_automation: 2.0.0
  download: 0.0.1+1
  diacritic: 0.1.3
  flutter_dotenv: 5.0.2
  cross_file: 0.3.3+1
  shake: 2.1.0
  profanity_filter: 2.0.0
  device_info_plus: 3.2.4
  file_picker: 4.6.1
  package_info_plus: 1.4.2
  cross_connectivity: 3.0.5
  linked_scroll_controller: 0.2.0
  just_audio: 0.9.27
  geolocator: 8.2.1
  image:
  msix: 2.8.18
  geocode: 1.0.1
  universal_platform: 1.0.0+1
  uni_links: 0.5.1
  sizer: 2.0.15
  rxdart: 0.27.4
  flutter_translator: ^0.1.7
  flutter_rating_bar: ^4.0.1

  dartz: 0.10.1

  # Storage
  hive: 2.2.2
  shared_preferences: 2.0.15

  # Code
  syntax_highlighter: 0.1.1
  flutter_highlight: 0.7.0
  dart_style: 2.2.3

  # Web
  js: 0.6.4
  #  flutter_js: 0.5.0+6

  # Payments
  purchases_flutter: 3.10.0

  # Lint
  very_good_analysis: 2.4.0

  # Adapty
  adapty_flutter: ^1.0.14

  # Share
  share: ^2.0.4

  # Responsive values / builder
  responsive_builder: ^0.4.3
  device_frame:
  reorderables:
  flutter_stripe: ^2.5.0
  flutter_stripe_web: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: 4.6.0
  flutter_gen_runner: 4.2.0

dependency_overrides:
  teta_core:
    path: ../../Teta/teta_core
  teta_cms:
    path: ../../teta-db
  teta_repositories:
    path: ../../Teta/teta_repositories

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/standard.png
    - assets/images/dark.png
    - assets/images/night.png
    - assets/images/retro.png
    - assets/images/silver.png
    - assets/images/aubergine.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
