import 'package:teta_widgets/src/elements/code/advanced/gridview.dart';
import 'package:teta_widgets/src/elements/code/advanced/gridview_builder.dart';
import 'package:teta_widgets/src/elements/code/advanced/listview.dart';
import 'package:teta_widgets/src/elements/code/advanced/listview_builder.dart';
import 'package:teta_widgets/src/elements/code/advanced/tcard.dart';
import 'package:teta_widgets/src/elements/code/advanced/tcard_builder.dart';
import 'package:teta_widgets/src/elements/code/templates/ad_mob_banner_ad_template.dart';
import 'package:teta_widgets/src/elements/code/templates/align.dart';
import 'package:teta_widgets/src/elements/code/templates/animated_align.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/anim_config_grid.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/anim_config_list.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/fade_in.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/scale.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/slide.dart';
import 'package:teta_widgets/src/elements/code/templates/aspect_ratio.dart';
import 'package:teta_widgets/src/elements/code/templates/audio_player_progress_indicator_template.dart';
import 'package:teta_widgets/src/elements/code/templates/audio_player_template.dart';
import 'package:teta_widgets/src/elements/code/templates/audio_player_volume_indicator_template.dart';
import 'package:teta_widgets/src/elements/code/templates/badge.dart';
import 'package:teta_widgets/src/elements/code/templates/bouncing_widget.dart';
import 'package:teta_widgets/src/elements/code/templates/button.dart';
import 'package:teta_widgets/src/elements/code/templates/card.dart';
import 'package:teta_widgets/src/elements/code/templates/center.dart';
import 'package:teta_widgets/src/elements/code/templates/checkbox.dart';
import 'package:teta_widgets/src/elements/code/templates/circular_progress_indicator.dart';
import 'package:teta_widgets/src/elements/code/templates/cms_count.dart';
import 'package:teta_widgets/src/elements/code/templates/cms_custom_query.dart';
import 'package:teta_widgets/src/elements/code/templates/cms_fetch.dart';
import 'package:teta_widgets/src/elements/code/templates/cms_logged_user.dart';
import 'package:teta_widgets/src/elements/code/templates/cms_stream.dart';
import 'package:teta_widgets/src/elements/code/templates/constrained_box.dart';
import 'package:teta_widgets/src/elements/code/templates/divider.dart';
import 'package:teta_widgets/src/elements/code/templates/fitted_box.dart';
import 'package:teta_widgets/src/elements/code/templates/future_builder.dart';
import 'package:teta_widgets/src/elements/code/templates/icon.dart';
import 'package:teta_widgets/src/elements/code/templates/icon_feather.dart';
import 'package:teta_widgets/src/elements/code/templates/icon_font_awesome.dart';
import 'package:teta_widgets/src/elements/code/templates/icon_line.dart';
import 'package:teta_widgets/src/elements/code/templates/opacity.dart';
import 'package:teta_widgets/src/elements/code/templates/placeholder.dart';
import 'package:teta_widgets/src/elements/code/templates/qonversion/qonversion_products.dart';
import 'package:teta_widgets/src/elements/code/templates/qonversion/qonversion_sub_status.dart';
import 'package:teta_widgets/src/elements/code/templates/qr.dart';
import 'package:teta_widgets/src/elements/code/templates/responsive/wrapper.dart';
import 'package:teta_widgets/src/elements/code/templates/responsive_condition.dart';
import 'package:teta_widgets/src/elements/code/templates/rotated_box.dart';
import 'package:teta_widgets/src/elements/code/templates/row.dart';
import 'package:teta_widgets/src/elements/code/templates/safearea.dart';
import 'package:teta_widgets/src/elements/code/templates/sizedbox.dart';
import 'package:teta_widgets/src/elements/code/templates/spacer.dart';
import 'package:teta_widgets/src/elements/code/templates/stack.dart';
import 'package:teta_widgets/src/elements/code/templates/stripe_cart_items_builder_template.dart';
import 'package:teta_widgets/src/elements/code/templates/stripe_products_builder_template.dart';
import 'package:teta_widgets/src/elements/code/templates/text.dart';
import 'package:teta_widgets/src/elements/code/templates/textfield.dart';
import 'package:teta_widgets/src/elements/code/templates/tooltip.dart';
import 'package:teta_widgets/src/elements/code/templates/twitter.dart';
import 'package:teta_widgets/src/elements/code/templates/video.dart';
import 'package:teta_widgets/src/elements/code/templates/visibility.dart';
import 'package:teta_widgets/src/elements/code/templates/web_view_x_template.dart';
import 'package:teta_widgets/src/elements/code/templates/wrap.dart';

///Tests for all widgets
void main() {
  AdMobBannerAdTemplate.testCode();
  AudioPlayerVolumeIndicatorTemplate.testCode();
  AudioPlayerProgressIndicatorTemplate.testCode();
  AudioPlayerTemplate.testCode();
  AlignCodeTemplate.testCode();
  AnimatedAlignCodeTemplate.testCode();
  AnimConfigGridCodeTemplate.testCode();
  AnimConfigListCodeTemplate.testCode();
  AspectRatioCodeTemplate.testCode();
  BadgeCodeTemplate.testCode();
  BouncingWidgetCodeTemplate.testCode();
  ButtonCodeTemplate.testCode();
  CardCodeTemplate.testCode();
  CenterCodeTemplate.testCode();
  CheckBoxCodeTemplate.testCode();
  CircularProgressIndicatorCodeTemplate.testCode();
  ConstrainedBoxCodeTemplate.testCode();
  CmsCountCodeTemplate.testCode();
  CmsCustomQueryCodeTemplate.testCode();
  CmsFetchCodeTemplate.testCode();
  CmsLoggedUserCodeTemplate.testCode();
  CmsStreamCodeTemplate.testCode();
  DividerCodeTemplate.testCode();
  FadeInCodeTemplate.testCode();
  FittedBoxCodeTemplate.testCode();
  IconCodeTemplate.testCode();
  IconFontAwesomeCodeTemplate.testCode();
  IconFeatherCodeTemplate.testCode();
  IconLineCodeTemplate.testCode();
  ListViewBuilderCodeTemplate.testCode();
  ListViewCodeTemplate.testCode();
  LoginTwitterCodeTemplate.testCode();
  OpacityCodeTemplate.testCode();
  PlaceholderCodeTemplate.testCode();
  QonversionProductsListCodeTemplate.testCode();
  QonversionSubsStatusCodeTemplate.testCode();
  QrCodeTemplate.testCode();
  GridViewBuilderCodeTemplate.testCode();
  GridViewCodeTemplate.testCode();
  RowCodeTemplate.testCode();
  RotatedBoxCodeTemplate.testCode();
  ResponsiveConditionCodeTemplate.testCode();
  ScaleCodeTemplate.testCode();
  SlideCodeTemplate.testCode();
  SpacerCodeTemplate.testCode();
  SizedBoxCodeTemplate.testCode();
  SafeAreaCodeTemplate.testCode();
  SupabaseFutureBuilderCodeTemplate.testCode();
  StripeProductsBuilderCodeTemplate.testCode();
  StripeCartItemsBuilderTemplate.testCode();
  StackCodeTemplate.testCode();
  TCardCodeTemplate.testCode();
  TCardBuilderCodeTemplate.testCode();
  TextCodeTemplate.testCode();
  TextFieldCodeTemplate.testCode();
  TooltipCodeTemplate.testCode();
  VisibilityCodeTemplate.testCode();
  WebViewXTemplate.testCode();
  WrapCodeTemplate.testCode();
  WrapperCodeTemplate.testCode();
  VideoCodeTemplate.testCode();
}
