import 'package:teta_widgets/src/elements/code/advanced/gridview.dart';
import 'package:teta_widgets/src/elements/code/advanced/gridview_builder.dart';
import 'package:teta_widgets/src/elements/code/advanced/listview_builder.dart';
import 'package:teta_widgets/src/elements/code/templates/ad_mob_banner_ad_template.dart';
import 'package:teta_widgets/src/elements/code/templates/align.dart';
import 'package:teta_widgets/src/elements/code/templates/animated_align.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/anim_config_grid.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/anim_config_list.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/fade_in.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/scale.dart';
import 'package:teta_widgets/src/elements/code/templates/animations/slide.dart';
import 'package:teta_widgets/src/elements/code/templates/aspect_ratio.dart';
import 'package:teta_widgets/src/elements/code/templates/badge.dart';
import 'package:teta_widgets/src/elements/code/templates/bouncing_widget.dart';
import 'package:teta_widgets/src/elements/code/templates/button.dart';
import 'package:teta_widgets/src/elements/code/templates/card.dart';
import 'package:teta_widgets/src/elements/code/templates/center.dart';
import 'package:teta_widgets/src/elements/code/templates/checkbox.dart';
import 'package:teta_widgets/src/elements/code/templates/circular_progress_indicator.dart';
import 'package:teta_widgets/src/elements/code/templates/icon.dart';
import 'package:teta_widgets/src/elements/code/templates/icon_feather.dart';
import 'package:teta_widgets/src/elements/code/templates/icon_font_awesome.dart';
import 'package:teta_widgets/src/elements/code/templates/icon_line.dart';
import 'package:teta_widgets/src/elements/code/templates/qr.dart';
import 'package:teta_widgets/src/elements/code/templates/text.dart';
import 'package:teta_widgets/src/elements/code/templates/textfield.dart';
import 'package:teta_widgets/src/elements/code/templates/tooltip.dart';
import 'package:teta_widgets/src/elements/code/templates/video.dart';
import 'package:teta_widgets/src/elements/code/templates/visibility.dart';
import 'package:teta_widgets/src/elements/code/templates/web_view_x_template.dart';
import 'package:teta_widgets/src/elements/code/templates/wrap.dart';

///Tests for all widgets toCode
void main() {
  AdMobBannerAdTemplate.testCode();
  AlignCodeTemplate.testCode();
  AnimatedAlignCodeTemplate.testCode();
  AnimConfigGridCodeTemplate.testCode();
  AnimConfigListCodeTemplate.testCode();
  AspectRatioCodeTemplate.testCode();
  BadgeCodeTemplate.testCode();
  BouncingWidgetCodeTemplate.testCode();
  ButtonCodeTemplate.testCode();
  CardCodeTemplate.testCode();
  CenterCodeTemplate.testCode();
  CheckBoxCodeTemplate.testCode();
  CircularProgressIndicatorCodeTemplate.testCode();
  FadeInCodeTemplate.testCode();
  IconCodeTemplate.testCode();
  IconFontAwesomeCodeTemplate.testCode();
  IconFeatherCodeTemplate.testCode();
  IconLineCodeTemplate.testCode();
  ListViewBuilderCodeTemplate.testCode();
  QrCodeTemplate.testCode();
  GridViewBuilderCodeTemplate.testCode();
  GridViewCodeTemplate.testCode();
  ScaleCodeTemplate.testCode();
  SlideCodeTemplate.testCode();
  TextCodeTemplate.testCode();
  TextFieldCodeTemplate.testCode();
  TooltipCodeTemplate.testCode();
  VisibilityCodeTemplate.testCode();
  WebViewXTemplate.testCode();
  WrapCodeTemplate.testCode();
  VideoCodeTemplate.testCode();
}
